# Generated by Django 4.1.4 on 2022-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.CharField(default='no_image.svg', max_length=25, verbose_name='Cover'),
        ),
    ]
